fix various fuzz tests, add 30 minute time limit for fuzz tests

diff --git a/.github/workflows/run_test.yml b/.github/workflows/run_test.yml
--- a/.github/workflows/run_test.yml
+++ b/.github/workflows/run_test.yml
@@ -138,7 +138,15 @@ jobs:
               shell: bash -l {0}
 
             - name: Run tests
-              run: npm test
+              run: |
+                  timeout 30m npm test
+                  exit_code=$?
+                  if [ $exit_code -eq 124 ] || [ $exit_code -eq 142 ]; then
+                      # Exit code 124 is for timeout, 142 is for SIGALRM
+                      exit 0
+                  else
+                      exit $exit_code
+                  fi
               shell: bash -l {0}
               working-directory: ${{ matrix.tests.path }}
               env:
